version: '3.5'
services:
# nodejs:
#   image: node:10.22.1-alpine3.11
#   container_name: api-nodejs
#   ports:
#    - 4200:4200
#   volumes:
#    - .:/app
#   depends_on:
#    - mongodb
#   command: npm start
 
 
  mongodb:
    image: mongo
    container_name: api-mongodb
    ports:
    - 27017:27017